# Generated by Django 6.0.6 on 2026-07-09 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asklens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AskLensQuery",
            fields=[],
            options={
                "verbose_name": "AskLens query",
                "verbose_name_plural": "AskLens queries",
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("asklens.semanticqueryrun",),
        ),
    ]
